AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  S3BucketName:
    Type: String
    Default: lever-jobs-data
    Description: S3 bucket name for storing scraped job data
  
  BackendApiEndpoint:
    Type: String
    Default: ""
    Description: Backend API endpoint for sending data to MongoDB

Resources:
  # S3 Bucket for data lake
  LeverJobsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldData
            Status: Enabled
            ExpirationInDays: 365
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Lambda Function
  LeverJobScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 900
      MemorySize: 512
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref LeverJobsBucket
          BACKEND_API_ENDPOINT: !Ref BackendApiEndpoint
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref LeverJobsBucket
        - CloudWatchLogsFullAccess
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
            Name: DailyLeverJobScraper
            Description: Daily execution of Lever job scraper
            Enabled: true

  # EventBridge Rule for scheduling
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Name: LeverJobScraperDailyRule
      Description: Triggers Lever job scraper daily
      ScheduleExpression: rate(1 day)
      State: ENABLED
      Targets:
        - Arn: !GetAtt LeverJobScraperFunction.Arn
          Id: LeverJobScraperTarget

  # Permission for EventBridge to invoke Lambda
  ScheduledRulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LeverJobScraperFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduledRule.Arn

Outputs:
  LeverJobsBucketName:
    Description: Name of the S3 bucket for storing job data
    Value: !Ref LeverJobsBucket
    Export:
      Name: LeverJobsBucketName

  LeverJobScraperFunctionArn:
    Description: ARN of the Lever job scraper Lambda function
    Value: !GetAtt LeverJobScraperFunction.Arn
    Export:
      Name: LeverJobScraperFunctionArn

  CloudWatchLogGroup:
    Description: CloudWatch Log Group for the Lambda function
    Value: !Sub "/aws/lambda/${LeverJobScraperFunction}"
    Export:
      Name: LeverJobScraperLogGroup 